version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      FL_OUTPUT_DIR: app/build
      FASTLANE_LANE: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - 1-gems-{{ checksum "Gemfile.lock" }}
            - jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: bundle check || bundle install --path vendor/bundle
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - run:
          command: cp $FL_OUTPUT_DIR/reports/report.junit $FL_OUTPUT_DIR/reports/results.xml
          when: always
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
